### ISSUE TITLE
For ADVERSARIAL ASR, "docker bulid" returned a non-zero code: 2 when "RUN pip install tensorflow-gpu==1.13.1" 

### ISSUE THREAD

**Issue by htZhang25** [cleverhans-lab/cleverhans#1174]
For examples/ADVERSARIAL ASR, "docker bulid" returned a non-zero code: 2 when "RUN pip install tensorflow-gpu==1.13.1 -i https://pypi.tuna.tsinghua.edu.cn/simple" 

**To Reproduce**
1. export LINGVO_DEVICE="gpu"
2. sudo docker build --no-cache --tag tensorflow:lingvo $(test "$LINGVO_DEVICE" = "gpu" && echo "--build-arg base_image=nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04") - < lingvo/docker/dev.dockerfile
4. See error (Note that I add -i https://pypi.tuna.tsinghua.edu.cn/simple in the line for installing tensorflow-gpu==1.13.1 since it is too slow, but it did not work after adding the new source. )
......
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting tensorflow-gpu==1.13.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/24/8c/459eb5fdaa8666010b6a32244ddb92f4015cfc54156d612959625096601d/tensorflow_gpu-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl (345.2 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirement
    hashes=hashes,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 259, in unpack_url
    hashes=hashes,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url
    link, downloader, temp_dir.path, hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 281, in _download_http_url
    for chunk in download.chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/progress_bars.py", line 166, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/network/utils.py", line 39, in response_chunks
    decode_content=False,
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/response.py", line 439, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.
The command '/bin/sh -c pip install tensorflow-gpu==1.13.1 -i https://pypi.tuna.tsinghua.edu.cn/simple' returned a non-zero code: 2

**System configuration**
 - ubuntu16.04
 - Python3.7

I hope someone can help me to deal with the question about "docker".

**Comment by jonasguan** [comment]
Hi @htZhang25 , unfortunately we can't provide support or maintenance for code in the `examples/` directory. If you were eventually able to solve the problem, we very much welcome a PR to help fix it.
