### ISSUE TITLE
Custom loss function in MIM in TF2

### ISSUE THREAD

**Issue by ypang6** [cleverhans-lab/cleverhans#1191]
**Describe the bug**
I encountered a tensor shape error when I was trying to generate MIM black-box attack on my test dataset in tf2. I'm not sure how to resolve this issue. The shape 12630 is the total number of test dataset. Is there anyone who is able to help? Thanks. 

**Code layout**
```
    def mim(self):
        # one-hot encode the testing labels
        numLabels = len(np.unique(self.testY))
        self.testY = to_categorical(self.testY, numLabels)

        return momentum_iterative_method(self.model, self.testX, eps=self.eps,
                                         eps_iter=0.06, nb_iter=10, norm=np.inf, targeted=False)
```
**Error**
  ```
Traceback (most recent call last):
  File "/media/ypang6/paralab/Research/Robustness/Keras/cnn_adv_test.py", line 105, in <module>
    blackbox(EPS=0.3, model_path=model_path, data_path=data_path).run_save(save_path)
  File "/media/ypang6/paralab/Research/Robustness/Keras/cnn_adv_test.py", line 83, in run_save
    np.save(save_path +'testX_mim.npy', self.mim())
  File "/media/ypang6/paralab/Research/Robustness/Keras/cnn_adv_test.py", line 59, in mim
    eps_iter=0.06, nb_iter=10, norm=np.inf, targeted=False)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/cleverhans/tf2/attacks/momentum_iterative_method.py", line 73, in momentum_iterative_method
    grad = compute_gradient(model_fn, adv_x, y, targeted)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/ypang6/anaconda3/lib/python3.7/site-packages/cleverhans/tf2/utils.py:133 compute_gradient  *
        loss = loss_fn(labels=y, logits=model_fn(x))
    /home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:976 __call__  **
        self.name)
    /home/ypang6/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:196 assert_input_compatibility
        str(x.shape.as_list()))

    ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=1. Full shape received: [12630]


Process finished with exit code 1


```
**System configuration**
 - Ubuntu 16.04 LTS
 - Python 3.7
 - TensorFlow 2.3.0

**Comment by ypang6** [comment]
I checked and found the issue comes from the function `compute_gradient`. In file 'momentum_iterative_method.py', 'Line 73' the function has four inputs 'grad = compute_gradient(model_fn, adv_x, y, targeted)'. In file 'utils.py', the function has five inputs 'compute_gradient(model_fn, loss_fn, x, y, targeted=False)'. The second input 'loss_fn' is missed.

**Comment by alkaet** [comment]
This should be a relatively simple fix. As far as I understand you would only need to add a loss_fn parameter to the MIM implementation and a default case corresponding to the MIM paper.
@ypang6 I'm not familiar with the MIM paper, what is the loss used in it?

**Comment by alkaet** [comment]
@ypang6  An example of the custom loss function definition is available in the Carlini & Wagner TF2 implementation if you would like to contribute.

**Comment by ypang6** [comment]
> This should be a relatively simple fix. As far as I understand you would only need to add `loss_fn` parameter to the MIM implementation and a default case corresponding to the MIM paper.
> @ypang6 I'm not familiar with the MIM paper, what is the loss used in it?

I think they are using softmax cross-entropy loss in the original MI-FGSM paper.

**Comment by ypang6** [comment]
> @ypang6 An example of the custom loss function definition is available in the Carlini & Wagner TF2 implementation if you would like to contribute.

I will have a look.

**Comment by alkaet** [comment]
> > This should be a relatively simple fix. As far as I understand you would only need to add `loss_fn` parameter to the MIM implementation and a default case corresponding to the MIM paper.
> 
> > @ypang6 I'm not familiar with the MIM paper, what is the loss used in it?
> 
> 
> 
> I think they are using softmax cross-entropy loss in the original MI-FGSM paper.

If that's the case the the CW attack implementation in tf2 should be sufficient as a reference

**Comment by ypang6** [comment]
> > > This should be a relatively simple fix. As far as I understand you would only need to add `loss_fn` parameter to the MIM implementation and a default case corresponding to the MIM paper.
> > 
> > 
> > > @ypang6 I'm not familiar with the MIM paper, what is the loss used in it?
> > 
> > 
> > I think they are using softmax cross-entropy loss in the original MI-FGSM paper.
> 
> If that's the case the the CW attack implementation in tf2 should be sufficient as a reference

I just made a pull request to fix the issue with several lines. Please have a look. Thanks,
